### ISSUE TITLE
MVP umbrella issue

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/eu-structural-funds#282]
@annafralberts @akariv @michaeljokf @ffalt @pwalsh 

This issue is an umbrella issue fo the [MVP milestone](https://github.com/os-data/eu-structural-funds/milestone/3) and includes:

- [x] #283 Ensure that all pipelines succeed 
- [x] #284 Concatenate all pipelines
- [x] #290 Parse amount and date columns
- [ ] #285 Assessment / improvement of current fiscal model
- [ ] #280 Data quality assurance

The deliverable is single dataset on Open-Spending covering all countries and regions with the following fields:

- total_amount 
- beneficiary_name
- project_name
- year 
- beneficiary_nuts_region
- funds_name
- program

**Comment by cyberbikepunk** [comment]
Aside writing processors to clean the data, we need to double-check whether all the mappings suggestions in the source files are correct. So I assign @michaeljokf and @annafralberts too on this one.

**Comment by cyberbikepunk** [comment]
Closing this as this is redundant with the [milestone](https://github.com/os-data/eu-structural-funds/milestone/3).
